# Generated by Django 5.2.5 on 2025-08-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedface',
            name='pose',
            field=models.CharField(default='front', max_length=16),
        ),
    ]
